VIA_ENABLE = yes
ENCODER_MAP_ENABLE = yes

VIAL_ENABLE = yes
VIAL_INSECURE = yes
ENCODER_ENABLE = yes

SPLIT_KEYBOARD = yes
SPLIT_TRANSPORT = i2c
SPLIT_LAYER_STATE_ENABLE = yes
SPLIT_OLED_ENABLE = yes
SPLIT_TRANSACTION_ENABLE = yes

CONSOLE_ENABLE = no
